import { describe, it, expect } from 'vitest'
import {
  generateChannelKeypairs,
  getPublicKey,
  MLKEM_PUBLIC_KEY_BYTES,
  MLKEM_SECRET_KEY_BYTES,
  DH_KEY_BYTES,
} from '../src/kem.js'
import { ChannelKeypairs, _getKeypairInternal } from '../src/types.js'
import { generateChannelKey } from '../src/channel.js'

describe('generateChannelKeypairs', () => {
  it('returns a ChannelKeypairs instance', () => {
    const kp = generateChannelKeypairs()
    expect(kp).toBeInstanceOf(ChannelKeypairs)
  })

  it('generates unique keypairs on each call', () => {
    const kp1 = generateChannelKeypairs()
    const kp2 = generateChannelKeypairs()
    const pub1 = getPublicKey(kp1)
    const pub2 = getPublicKey(kp2)
    // Public keys should differ (extremely high probability)
    expect(pub1.mlkem).not.toEqual(pub2.mlkem)
    expect(pub1.dh).not.toEqual(pub2.dh)
  })

  it('internal ML-KEM-1024 public key is 1568 bytes', () => {
    const kp = generateChannelKeypairs()
    const internal = _getKeypairInternal(kp)
    expect(internal.mlkem.publicKey.length).toBe(MLKEM_PUBLIC_KEY_BYTES)
  })

  it('internal ML-KEM-1024 secret key is 3168 bytes', () => {
    const kp = generateChannelKeypairs()
    const internal = _getKeypairInternal(kp)
    expect(internal.mlkem.secretKey.length).toBe(MLKEM_SECRET_KEY_BYTES)
  })

  it('internal X25519 public key is 32 bytes', () => {
    const kp = generateChannelKeypairs()
    const internal = _getKeypairInternal(kp)
    expect(internal.dh.publicKey.length).toBe(DH_KEY_BYTES)
  })

  it('internal X25519 secret key is 32 bytes', () => {
    const kp = generateChannelKeypairs()
    const internal = _getKeypairInternal(kp)
    expect(internal.dh.secretKey.length).toBe(DH_KEY_BYTES)
  })
})

describe('getPublicKey', () => {
  it('returns only public key material', () => {
    const kp = generateChannelKeypairs()
    const pub = getPublicKey(kp)
    expect(pub.mlkem.length).toBe(MLKEM_PUBLIC_KEY_BYTES)
    expect(pub.dh.length).toBe(DH_KEY_BYTES)
    // Public key type should not have a secretKey field
    expect('secretKey' in pub).toBe(false)
  })

  it('returns the same public keys on repeated calls', () => {
    const kp = generateChannelKeypairs()
    const pub1 = getPublicKey(kp)
    const pub2 = getPublicKey(kp)
    expect(pub1.mlkem).toEqual(pub2.mlkem)
    expect(pub1.dh).toEqual(pub2.dh)
  })

  it('propagates optional id field from getPublicKey call', () => {
    // id is set by the caller on ChannelPublicKey, not generated by getPublicKey
    const kp = generateChannelKeypairs()
    const pub = getPublicKey(kp)
    pub.id = 'alice@example.com'
    expect(pub.id).toBe('alice@example.com')
  })
})

describe('generateChannelKey', () => {
  it('returns 32 bytes', () => {
    expect(generateChannelKey().length).toBe(32)
  })

  it('generates unique keys on each call', () => {
    const k1 = generateChannelKey()
    const k2 = generateChannelKey()
    expect(k1).not.toEqual(k2)
  })
})
